[tools]
ruff = "latest"
uv = "0.12.12"

[settings]
python.uv_venv_auto = "create|source"

[tasks.test]
run = 'uv run python -m unittest discover -s tests -t .'

[tasks.test-docker]
run = 'docker build --target test .'

[tasks.coverage]
run = '''
#!/usr/bin/env bash
uv run coverage run -m unittest discover -s tests -t .
uv run coverage report -m
'''
